#!/usr/bin/env python3
"""Generate calendar.ics and CALENDAR.md from events.json.

Usage: python3 scripts/build.py  (run from the repo root)
"""
import json
import sys
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TZID = "America/Los_Angeles"

VTIMEZONE = """BEGIN:VTIMEZONE
TZID:America/Los_Angeles
BEGIN:DAYLIGHT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
TZNAME:PDT
DTSTART:19700308T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
TZNAME:PST
DTSTART:19701101T020000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD
END:VTIMEZONE"""

GENRE_EMOJI = {
    "techno": "🔊", "house": "🏠", "edm": "🎆", "amapiano": "🪘",
    "afrobeats": "🪘", "dnb": "🥁", "boat": "⛵", "day-party": "☀️",
    "festival": "🎪",
}


def esc(text):
    return (text.replace("\\", "\\\\").replace(";", "\\;")
                .replace(",", "\\,").replace("\n", "\\n"))


def fold(line):
    """RFC 5545 line folding at 74 octets."""
    out = []
    raw = line.encode("utf-8")
    while len(raw) > 74:
        cut = 74
        while cut > 0 and (raw[cut] & 0xC0) == 0x80:  # don't split UTF-8 chars
            cut -= 1
        out.append(raw[:cut].decode("utf-8"))
        raw = b" " + raw[cut:]
    out.append(raw.decode("utf-8"))
    return "\r\n".join(out)


def dt_local(d, hm):
    return f"{d.replace('-', '')}T{hm.replace(':', '')}00"


def event_lines(ev, dtstamp):
    lines = ["BEGIN:VEVENT",
             f"UID:{ev['id']}@bay-events.cameronking",
             f"DTSTAMP:{dtstamp}"]
    d = ev["date"]
    start, end = ev.get("start"), ev.get("end")
    if start:
        lines.append(f"DTSTART;TZID={TZID}:{dt_local(d, start)}")
        end_day = d
        if end:
            if end <= start:  # crosses midnight
                end_day = (date.fromisoformat(d) + timedelta(days=1)).isoformat()
            lines.append(f"DTEND;TZID={TZID}:{dt_local(end_day, end)}")
        # no explicit end: leave DTEND out (point-in-time per RFC 5545)
    else:  # all-day (single or multi-day)
        last = ev.get("end_date", d)
        dtend = (date.fromisoformat(last) + timedelta(days=1)).isoformat()
        lines.append(f"DTSTART;VALUE=DATE:{d.replace('-', '')}")
        lines.append(f"DTEND;VALUE=DATE:{dtend.replace('-', '')}")
    if ev.get("recur"):
        r = ev["recur"]
        until = r["until"].replace("-", "")
        lines.append(f"RRULE:FREQ={r['freq']};BYDAY={r['byday']};UNTIL={until}T235959Z")

    lines.append(f"SUMMARY:{esc(ev['title'])}")
    loc = ", ".join(x for x in [ev.get("venue"), ev.get("city")] if x and x != "TBA")
    if loc:
        lines.append(f"LOCATION:{esc(loc)}")
    desc = []
    if ev.get("genres"):
        desc.append("Genres: " + ", ".join(ev["genres"]))
    if ev.get("notes"):
        desc.append(ev["notes"])
    if ev.get("approx"):
        desc.append("Time approximate — check ticket link.")
    if ev.get("status") == "likely":
        desc.append("Status: LIKELY (single source) — verify before going.")
    if ev.get("url"):
        desc.append("Tickets/info: " + ev["url"])
    if desc:
        lines.append(f"DESCRIPTION:{esc(' | '.join(desc))}")
    if ev.get("url"):
        lines.append(f"URL:{ev['url']}")
    if ev.get("genres"):
        lines.append("CATEGORIES:" + ",".join(g.upper() for g in ev["genres"]))
    status = {"cancelled": "CANCELLED", "likely": "TENTATIVE"}.get(ev.get("status"), "CONFIRMED")
    lines.append(f"STATUS:{status}")
    lines.append("END:VEVENT")
    return lines


def build_ics(data):
    dtstamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    meta = data["meta"]
    lines = ["BEGIN:VCALENDAR", "VERSION:2.0",
             "PRODID:-//bay-events//Bay Area Electronic Events//EN",
             "CALSCALE:GREGORIAN", "METHOD:PUBLISH",
             f"X-WR-CALNAME:{esc(meta['calname'])}",
             f"X-WR-CALDESC:{esc(meta['caldesc'])}",
             f"X-WR-TIMEZONE:{TZID}",
             "REFRESH-INTERVAL;VALUE=DURATION:PT12H"]
    lines += VTIMEZONE.split("\n")
    for ev in data["events"]:
        if ev.get("status") == "removed":
            continue
        lines += event_lines(ev, dtstamp)
    lines.append("END:VCALENDAR")
    return "\r\n".join(fold(l) for l in lines) + "\r\n"


def build_md(data):
    events = [e for e in data["events"] if e.get("status") != "removed"]
    singles = sorted((e for e in events if not e.get("recur")), key=lambda e: (e["date"], e.get("start") or "99"))
    recurring = [e for e in events if e.get("recur")]
    out = ["# Bay Area Electronic Events",
           "",
           f"_{data['meta']['caldesc']}_",
           "",
           "**Subscribe:** see [README](README.md). Generated from `events.json` — do not edit this file by hand.",
           ""]
    if recurring:
        out.append("## Weekly / recurring")
        out.append("")
        for e in recurring:
            r = e["recur"]
            em = "".join(dict.fromkeys(GENRE_EMOJI.get(g, "") for g in e.get("genres", [])))
            out.append(f"- **{r['byday']} weekly until {r['until']}** — {e['title']} — {e.get('venue', '')}, {e.get('city', '')} {em} ([info]({e.get('url', '')}))")
        out.append("")
    month = None
    for e in singles:
        d = date.fromisoformat(e["date"])
        m = d.strftime("%B %Y")
        if m != month:
            month = m
            out += [f"## {m}", ""]
        day = d.strftime("%a %b %-d")
        span = ""
        if e.get("end_date"):
            span = f"–{date.fromisoformat(e['end_date']).strftime('%-d')}"
        t = f" {e['start']}" if e.get("start") else ""
        em = "".join(dict.fromkeys(GENRE_EMOJI.get(g, "") for g in e.get("genres", [])))
        flags = []
        if e.get("status") == "likely":
            flags.append("_unconfirmed_")
        if e.get("status") == "cancelled":
            flags.append("**CANCELLED**")
        flag = (" " + " ".join(flags)) if flags else ""
        link = f" ([tickets]({e['url']}))" if e.get("url") else ""
        note = f" — {e['notes']}" if e.get("notes") else ""
        out.append(f"- **{day}{span}**{t} — {e['title']} — {e.get('venue', 'TBA')}, {e.get('city', '')} {em}{flag}{link}{note}")
    out.append("")
    return "\n".join(out)


def main():
    data = json.loads((ROOT / "events.json").read_text())
    ids = [e["id"] for e in data["events"]]
    dupes = {i for i in ids if ids.count(i) > 1}
    if dupes:
        sys.exit(f"ERROR: duplicate event ids: {dupes}")
    for e in data["events"]:
        date.fromisoformat(e["date"])  # validate
        if e.get("end_date"):
            assert e["end_date"] >= e["date"], f"end_date before date: {e['id']}"
    with open(ROOT / "calendar.ics", "w", newline="") as f:
        f.write(build_ics(data))
    (ROOT / "CALENDAR.md").write_text(build_md(data))
    n = len([e for e in data['events'] if e.get('status') != 'removed'])
    print(f"OK: wrote calendar.ics + CALENDAR.md ({n} events)")


if __name__ == "__main__":
    main()
